# Generated by Django 4.2.7 on 2026-04-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0006_alter_algorithm_code_alter_algorithm_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='algorithm',
            name='algorithms__status_9941b7_idx',
        ),
    ]
